#!/usr/bin/env bash
# Regenerates the typed ABI consumed by web/ and functions/ after a contract change.
set -euo pipefail
cd "$(dirname "$0")"
forge build --silent
ABI=$(jq '.abi' out/MarfaSpiritMembership.sol/MarfaSpiritMembership.json)
OUT="// Auto-generated by contracts/export-abi.sh — do not edit.
export const membershipAbi = ${ABI} as const;
"
echo "$OUT" > ../shared/membershipAbi.ts
echo "wrote shared/membershipAbi.ts"
